// MLModelManager.swift
// Brabus — On-Device Document Intelligence Assistant
//
// Loads BrabusDocumentClassifier.mlmodel and runs on-device inference.
//
// HOW TO ADD THE MODEL IN XCODE:
//   1. Run the Python pipeline:  python convert_to_coreml.py
//   2. The output file is: ios/Brabus/Models/BrabusDocumentClassifier.mlmodel
//   3. Open your Xcode project.
//   4. Drag BrabusDocumentClassifier.mlmodel into the Project Navigator.
//   5. In the file inspector panel (right side), check that the Brabus
//      app target is listed under "Target Membership".
//   6. Xcode auto-generates a Swift class named BrabusDocumentClassifier.
//   7. Build the project — no other changes needed.
//
// The model expects a 1×12 Float32 input named "document_features".
// Features must be normalised using the means and stds from
// brabus_pytorch_metadata.json before passing to the model.

import CoreML
import Foundation

// MARK: - Model Manager

final class MLModelManager {

    // MARK: - Normalisation parameters
    // These values are saved by train_pytorch.py into brabus_pytorch_metadata.json
    // and embedded into the Core ML model's user-defined metadata.
    // Update these if you retrain the model.
    // Generated by train_pytorch.py — see ml/models/brabus_pytorch_metadata.json
    // Re-run python train_pytorch.py and update these values if you retrain the model.
    // Feature order: character_count, word_count, sentence_count, date_count,
    //   email_count, phone_count, dollar_amount_count, action_word_count,
    //   education_keyword_count, job_keyword_count, receipt_keyword_count, deadline_keyword_count
    private let normMeans: [Float] = [
        521.1299, 78.375, 7.6169, 1.4878,
        0.694, 0.0268, 0.987, 2.5268,
        3.0471, 1.875, 1.5235, 0.819
    ]

    private let normStds: [Float] = [
        141.3179, 21.8047, 2.5151, 1.0256,
        0.6824, 0.1615, 1.6479, 1.4007,
        2.8688, 2.6228, 2.6132, 0.7189
    ]

    // Ordered label list — must match the "labels" array in brabus_pytorch_metadata.json
    private let labels: [String] = [
        "assignment_sheet",
        "event_flyer",
        "general_notes",
        "job_posting",
        "receipt",
        "scholarship_notice",
        "syllabus",
    ]

    // MARK: - Model

    // TODO: Once you have added BrabusDocumentClassifier.mlmodel to Xcode,
    // replace the lazy var below with the Xcode-generated class:
    //
    //   private lazy var model: BrabusDocumentClassifier? = {
    //       try? BrabusDocumentClassifier(configuration: MLModelConfiguration())
    //   }()
    //
    // The current implementation uses MLModel directly so the project
    // compiles even before the .mlmodel file is added to Xcode.
    private lazy var model: MLModel? = {
        guard let url = Bundle.main.url(
            forResource: "BrabusDocumentClassifier",
            withExtension: "mlmodelc"
        ) ?? Bundle.main.url(
            forResource: "BrabusDocumentClassifier",
            withExtension: "mlmodel"
        ) else {
            return nil
        }
        return try? MLModel(contentsOf: url, configuration: MLModelConfiguration())
    }()

    // MARK: - Inference

    /// Runs on-device inference on the given document text.
    /// Returns a PredictionResult; falls back to a heuristic if the model is unavailable.
    func predict(text: String) -> PredictionResult {
        let rawFeatures = DocumentFeatureExtractor.featureVector(for: text)
        let normalised = normalise(rawFeatures)

        // Attempt Core ML inference
        if let result = runCoreML(features: normalised) {
            return result
        }

        // Heuristic fallback when .mlmodel is not yet added to Xcode
        return heuristicPrediction(features: rawFeatures)
    }

    // MARK: - Core ML call

    private func runCoreML(features: [Float]) -> PredictionResult? {
        guard let model else { return nil }

        do {
            // Build the input dictionary with a 1×12 MLMultiArray
            guard let multiArray = try? MLMultiArray(
                shape: [1, NSNumber(value: features.count)],
                dataType: .float32
            ) else { return nil }

            for (i, value) in features.enumerated() {
                multiArray[i] = NSNumber(value: value)
            }

            let input = try MLDictionaryFeatureProvider(
                dictionary: ["document_features": multiArray]
            )
            let output = try model.prediction(from: input)

            // Extract raw logit output (varies by coremltools version)
            // Try common output feature names
            let outputNames = ["var_\(features.count)", "linear_2", "output", "classLabel"]
            var logits: [Float]?

            for name in outputNames {
                if let arr = output.featureValue(for: name)?.multiArrayValue {
                    logits = (0..<arr.count).map { arr[$0].floatValue }
                    break
                }
            }

            // If none of the hard-coded names matched, use whatever the first output is
            if logits == nil {
                if let firstName = model.modelDescription.outputDescriptionsByName.keys.first,
                   let arr = output.featureValue(for: firstName)?.multiArrayValue {
                    logits = (0..<arr.count).map { arr[$0].floatValue }
                }
            }

            guard let logits else { return nil }
            let probs = softmax(logits)
            let maxIdx = probs.indices.max(by: { probs[$0] < probs[$1] }) ?? 0
            let label = maxIdx < labels.count ? labels[maxIdx] : "unknown"
            let confidence = Double(probs[maxIdx])

            return PredictionResult(
                documentType: DocumentType.from(rawValue: label),
                confidence: confidence,
                isConfident: confidence >= 0.60
            )
        } catch {
            return nil
        }
    }

    // MARK: - Heuristic fallback

    /// Simple keyword-voting classifier used when the Core ML model is not
    /// available (e.g., during development before .mlmodel is added to Xcode).
    private func heuristicPrediction(features: [Float]) -> PredictionResult {
        let educationScore  = features[8]   // education_keyword_count
        let jobScore        = features[9]   // job_keyword_count
        let receiptScore    = features[10]  // receipt_keyword_count
        let deadlineScore   = features[11]  // deadline_keyword_count
        let dollarScore     = features[6]   // dollar_amount_count
        let actionScore     = features[7]   // action_word_count

        var scores: [(DocumentType, Float)] = [
            (.syllabus,          educationScore * 1.5 + deadlineScore),
            (.assignmentSheet,   deadlineScore * 2.0 + actionScore),
            (.eventFlyer,        actionScore * 1.2),
            (.receipt,           receiptScore * 2.0 + dollarScore * 1.5),
            (.scholarshipNotice, educationScore + deadlineScore * 1.5 + dollarScore),
            (.jobPosting,        jobScore * 2.0),
            (.generalNotes,      1.0),  // default floor
        ]

        scores.sort { $0.1 > $1.1 }
        let best = scores.first!
        return PredictionResult(
            documentType: best.0,
            confidence: -1,      // confidence unavailable in heuristic mode
            isConfident: false
        )
    }

    // MARK: - Normalisation

    private func normalise(_ features: [Float]) -> [Float] {
        precondition(features.count == normMeans.count,
                     "Feature count mismatch: expected \(normMeans.count), got \(features.count)")
        return zip(features, zip(normMeans, normStds)).map { raw, meanStd in
            let (mean, std) = meanStd
            return (raw - mean) / (std + 1e-8)
        }
    }

    // MARK: - Softmax

    private func softmax(_ logits: [Float]) -> [Float] {
        let maxVal = logits.max() ?? 0
        let exps = logits.map { expf($0 - maxVal) }
        let sum = exps.reduce(0, +)
        return exps.map { $0 / (sum + 1e-8) }
    }
}
